// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMDno-Wb8MmBunXh4e7FjrX4zNv3Pj8g',
    appId: '1:423796998013:web:22919be4f9d761a280d614',
    messagingSenderId: '423796998013',
    projectId: 'flutteremart-19106',
    authDomain: 'flutteremart-19106.firebaseapp.com',
    storageBucket: 'flutteremart-19106.firebasestorage.app',
    measurementId: 'G-N0R50NRLEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2bA3d9OO7MAdQI0ezrQ9uuVoioWh7HAM',
    appId: '1:423796998013:android:ab31c62a308e30c280d614',
    messagingSenderId: '423796998013',
    projectId: 'flutteremart-19106',
    storageBucket: 'flutteremart-19106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhxA-PMeBYJ_UuuKA2W4SVg25EpMPxE_Q',
    appId: '1:423796998013:ios:7abf85ab155a87e180d614',
    messagingSenderId: '423796998013',
    projectId: 'flutteremart-19106',
    storageBucket: 'flutteremart-19106.firebasestorage.app',
    iosBundleId: 'com.example.flutterEmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhxA-PMeBYJ_UuuKA2W4SVg25EpMPxE_Q',
    appId: '1:423796998013:ios:7abf85ab155a87e180d614',
    messagingSenderId: '423796998013',
    projectId: 'flutteremart-19106',
    storageBucket: 'flutteremart-19106.firebasestorage.app',
    iosBundleId: 'com.example.flutterEmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqMDno-Wb8MmBunXh4e7FjrX4zNv3Pj8g',
    appId: '1:423796998013:web:395eac30adf5a26580d614',
    messagingSenderId: '423796998013',
    projectId: 'flutteremart-19106',
    authDomain: 'flutteremart-19106.firebaseapp.com',
    storageBucket: 'flutteremart-19106.firebasestorage.app',
    measurementId: 'G-4F8Q33NS11',
  );
}
